import { observable } from "mobx";
import firebase from "firebase/app";
import "firebase/firestore";
import { initFirestorter, Document } from "firestorter";
import config from "../firebase-config";

!firebase.apps.length ? firebase.initializeApp(config) : firebase.app();

initFirestorter({ firebase: firebase });
// let templateId;

// const UiStore = new Document({ mode: "on" });
const UiStore = new observable({
  UiData: new Document({ mode: "auto" }),
  isLive: true,
  hasMenu: false,
  devMode: true,
  defaultScores: {
    fancyScores: {
      top10: {
        points: 100,
        description: "Top 10 Fancy",
        category: "fancy",
        type: "every"
      },
      top1: {
        points: 1000,
        description: "First Fancy",
        category: "fancy",
        type: "every"
      },
      top100: {
        points: 20,
        description: "Top 100 Fancy",
        category: "fancy",
        type: "every"
      },
      fancyKitty: {
        points: 10,
        description: "Fancy",
        category: "fancy",
        type: "every"
      }
    },
    prestigeScores: {
      top10: {
        points: 100,
        description: "Top 10 Prestige",
        category: "prestige",
        type: "every"
      },
      top1: {
        points: 1000,
        description: "First Prestige",
        category: "prestige",
        type: "every"
      },
      top100: {
        points: 20,
        description: "Top 100 Prestige",
        category: "prestige",
        type: "every"
      },
      prestigeKitty: {
        points: 10,
        description: "Fancy",
        category: "prestige",
        type: "every"
      }
    },
    idScores: {
      top1000: {
        points: 1000,
        description: "First 1000 kitties",
        category: "idNumber",
        type: "every"
      },
      id1000: {
        points: 1000,
        target: 1000,
        description: "Is id 1000",
        category: "idNumber",
        type: "portfolio"
      },
      id10000: {
        points: 1000,
        target: 10000,
        description: "Is id 10000",
        category: "idNumber",
        type: "portfolio"
      },
      id12345: {
        points: 1000,
        target: 12345,
        description: "Is id 12345",
        category: "idNumber",
        type: "portfolio"
      },
      id123456: {
        points: 1000,
        target: 123456,
        description: "Is id 123456",
        category: "idNumber",
        type: "portfolio"
      }
    },
    colorScores: {
      color: {
        points: 10,
        description: "A kitty is this color",
        category: "color",
        type: "portfolio"
      },
      allColorBonus: {
        points: 500,
        description: "Has all Colors",
        target: 31,
        category: "color",
        type: "portfolio"
      }
    },
    generatonScores: {
      generation: {
        points: 10,
        description: "A kitty is this generation",
        category: "generation",
        type: "portfolio"
      },
      allGenBonus: {
        points: 500,
        description: "Has all top 24 generations",
        target: 23,
        category: "generation",
        type: "portfolio"
      },
      above1000Bonus: {
        points: 500,
        description: "Has a generation higher than 1000",
        target: 500,
        category: "generation",
        type: "portfolio"
      }
    },
    vintageScores: {
      hasVintage: {
        points: 500,
        description: "Has a Vintage Kitty",
        category: "vintage",
        type: "portfolio"
      }
    }
  },
  vintageConditions: {
    colorprimary: ["cloudwhite", "greymatter", "koala", "onyx", "shadowgrey"],
    colorsecondary: ["cyborg", "egyptiankohl", "lilac", "pearl", "wolfgrey"],
    colortertiary: ["cashewmilk", "granitegrey", "icy", "purplehaze", "shale"],
    coloreyes: ["eclipse", "thundergrey"]
  },
  allFancies: [
    { value: "Gwendolion", label: "Gwendolion" },
    { value: "Catseye", label: "Catseye" },
    { value: "Skeletonne", label: "Skeletonne" },
    { value: "Furmione", label: "Furmione" },
    { value: "Jack", label: "Jack" },
    { value: "Pawderick", label: "Pawderick" },
    { value: "Al", label: "Al" },
    { value: "Ande", label: "Ande" },
    { value: "Atlas", label: "Atlas" },
    { value: "Berry", label: "Berry" },
    { value: "Boot", label: "Boot" },
    { value: "Catamari", label: "Catamari" },
    { value: "Catbury", label: "Catbury" },
    { value: "Catyrax", label: "Catyrax" },
    { value: "ChatPlongeur", label: "ChatPlongeur" },
    { value: "Clover", label: "Clover" },
    { value: "Curdlin", label: "Curdlin" },
    { value: "DJMeowlody", label: "DJMeowlody" },
    { value: "DocPurr", label: "DocPurr" },
    { value: "Draco", label: "Draco" },
    { value: "DracoJunior", label: "DracoJunior" },
    { value: "Dracula", label: "Dracula" },
    { value: "Dreggo", label: "Dreggo" },
    { value: "DuCat", label: "DuCat" },
    { value: "Dukecat", label: "Dukecat" },
    { value: "Earnie", label: "Earnie" },
    { value: "Flutterbee", label: "Flutterbee" },
    { value: "Furbeard", label: "Furbeard" },
    { value: "Furrmingo", label: "Furrmingo" },
    { value: "GeneDough", label: "GeneDough" },
    { value: "Glasswalker", label: "Glasswalker" },
    { value: "Glitter", label: "Glitter" },
    { value: "Kitijira", label: "Kitijira" },
    {
      value: "KittyFormerlyKnownAsPrince",
      label: "KittyFormerlyKnownAsPrince"
    },
    { value: "KittyPride", label: "KittyPride" },
    { value: "Krakitten", label: "Krakitten" },
    { value: "Lulu", label: "Lulu" },
    { value: "Magmeow", label: "Magmeow" },
    { value: "Meowstro", label: "Meowstro" },
    { value: "MissPurrfect", label: "MissPurrfect" },
    { value: "MisterPurrfect", label: "MisterPurrfect" },
    { value: "Mistletoe", label: "Mistletoe" },
    { value: "Momo-chan", label: "Momo-chan" },
    { value: "Negato", label: "Negato" },
    { value: "Robin", label: "Robin" },
    { value: "Page", label: "Page" },
    { value: "Pawrula", label: "Pawrula" },
    { value: "Pawzilla", label: "Pawzilla" },
    { value: "PhuZiqaat", label: "PhuZiqaat" },
    { value: "Pickles", label: "Pickles" },
    { value: "Pizzazz", label: "Pizzazz" },
    { value: "PoisonOrchid", label: "PoisonOrchid" },
    { value: "Purrity", label: "Purrity" },
    { value: "Purrspero", label: "Purrspero" },
    { value: "PussForProgress", label: "PussForProgress" },
    { value: "Raspoutine", label: "Raspoutine" },
    { value: "SantaClaws", label: "SantaClaws" },
    { value: "SchrödingersCat", label: "SchrödingersCat" },
    { value: "SheilaPurren", label: "SheilaPurren" },
    { value: "ShipCat", label: "ShipCat" },
    { value: "Squib", label: "Squib" },
    { value: "Squiddlesworth", label: "Squiddlesworth" },
    { value: "Stitches", label: "Stitches" },
    { value: "Swish", label: "Swish" },
    { value: "Tabby", label: "Tabby" },
    { value: "TallyThePurrocious", label: "TallyThePurrocious" },
    { value: "Vernon", label: "Vernon" },
    { value: "Whisper", label: "Whisper" },
    { value: "YuriCatsuki", label: "YuriCatsuki" },
    { value: "咚咚锵", label: "DancingLion" },
    { value: "汪星爷", label: "Dogcat" },
    { value: "红包喵", label: "LuckyCat" }
  ],
  allPrestiges: [
    { value: "aegis", label: "aegis" },
    { value: "alpacacino", label: "alpacacino" },
    { value: "alpunka", label: "alpunka" },
    { value: "beatlesque", label: "beatlesque" },
    { value: "bionic", label: "bionic" },
    { value: "brassard", label: "brassard" },
    { value: "catterypack", label: "catterypack" },
    { value: "centurion", label: "centurion" },
    { value: "cindylou", label: "cindylou" },
    { value: "dominator", label: "dominator" },
    { value: "dreamcloud", label: "dreamcloud" },
    { value: "duckduckcat", label: "duckduckcat" },
    { value: "explorer", label: "explorer" },
    { value: "fileshare", label: "fileshare" },
    { value: "furball", label: "furball" },
    { value: "gauntlet", label: "gauntlet" },
    { value: "guard", label: "guard" },
    { value: "holidaycheer", label: "holidaycheer" },
    { value: "hooked", label: "hooked" },
    { value: "huacool", label: "huacool" },
    { value: "inaband", label: "inaband" },
    { value: "landlubber", label: "landlubber" },
    { value: "lit", label: "lit" },
    { value: "maraud", label: "maraud" },
    { value: "oohshiny", label: "oohshiny" },
    { value: "pawsfree", label: "pawsfree" },
    { value: "prune", label: "prune" },
    { value: "purrbados", label: "purrbados" },
    { value: "purrior", label: "purrior" },
    { value: "reindeer", label: "reindeer" },
    { value: "scout", label: "scout" },
    { value: "scratchingpost", label: "scratchingpost" },
    { value: "squelch", label: "squelch" },
    { value: "thatsawrap", label: "thatsawrap" },
    { value: "timbers", label: "timbers" },
    { value: "uplink", label: "uplink" },
    { value: "velite", label: "velite" },
    { value: "werekitty", label: "werekitty" },
    { value: "wrecked", label: "wrecked" }
  ],
  allAttributes: [
    "fangtastic",
    "pixiebob",
    "emeraldgreen",
    "tongue",
    "greymatter",
    "totesbasic",
    "palejade",
    "cyborg",
    "floorislava",
    "majestic",
    "buzzed",
    "manul",
    "dahlia",
    "norwegianforest",
    "sully",
    "rollercoaster",
    "harbourfog",
    "persian",
    "safetyvest",
    "seafoam",
    "inflatablepool",
    "prism",
    "wiley",
    "walrus",
    "sizzurp",
    "wyrm",
    "redvelvet",
    "hyacinth",
    "juju",
    "dali",
    "asif",
    "hotrod",
    "cashewmilk",
    "leopard",
    "limegreen",
    "unicorn",
    "lynx",
    "myparade",
    "buttercup",
    "icicle",
    "scorpius",
    "universe",
    "meowgarine",
    "wonky",
    "olive",
    "wowza",
    "swampgreen",
    "icy",
    "gyre",
    "kittencream",
    "otaku",
    "twilightsparkle",
    "bornwithit",
    "alien",
    "ruhroh",
    "mekong",
    "pumpkin",
    "ducky",
    "struck",
    "shadowgrey",
    "fox",
    "slyboots",
    "ganado",
    "drift",
    "strawberry",
    "splat",
    "swarley",
    "chronic",
    "featherbrain",
    "bridesmaid",
    "soserious",
    "calicool",
    "frozen",
    "shamrock",
    "downbythebay",
    "parakeet",
    "balinese",
    "cheeky",
    "royalpurple",
    "sphynx",
    "onyx",
    "kaleidoscope",
    "coffee",
    "foghornpawhorn",
    "littlefoot",
    "highlander",
    "orangesoda",
    "tinybox",
    "cymric",
    "daemonwings",
    "shale",
    "laperm",
    "pinefresh",
    "violet",
    "secretgarden",
    "azaleablush",
    "sandalwood",
    "finalfrontier",
    "happygokitty",
    "oasis",
    "fallspice",
    "babypuke",
    "junglebook",
    "rosequartz",
    "lykoi",
    "saycheese",
    "glacier",
    "pearl",
    "himalayan",
    "barkbrown",
    "dioscuri",
    "tiger",
    "dragonwings",
    "dreamboat",
    "martian",
    "allyouneed",
    "daffodil",
    "amur",
    "fabulous",
    "forgetmenot",
    "burmilla",
    "grim",
    "serpent",
    "sass",
    "belleblue",
    "firstblush",
    "topoftheworld",
    "satiated",
    "ooze",
    "chameleon",
    "henna",
    "koala",
    "chantilly",
    "impish",
    "oldlace",
    "bobtail",
    "salty",
    "firedup",
    "tundra",
    "coralsunrise",
    "cloudwhite",
    "dragontail",
    "lemonade",
    "avatar",
    "chartreux",
    "wingtips",
    "royalblue",
    "flamingo",
    "autumnmoon",
    "neckbeard",
    "rascal",
    "aflutter",
    "sweetmeloncakes",
    "dragonfruit",
    "oceanid",
    "rorschach",
    "dune",
    "gold",
    "cinderella",
    "spangled",
    "chestnut",
    "googly",
    "isotope",
    "mauveover",
    "starstruck",
    "granitegrey",
    "koladiviya",
    "mertail",
    "springcrocus",
    "luckystripe",
    "mallowflower",
    "ragdoll",
    "dippedcone",
    "bubblegum",
    "delite",
    "aquamarine",
    "munchkin",
    "gemini",
    "highsociety",
    "kurilian",
    "kalahari",
    "poisonberry",
    "elk",
    "gerbil",
    "roadtogold",
    "savannah",
    "selkirk",
    "jacked",
    "drama",
    "yokel",
    "ragamuffin",
    "cerulian",
    "cobalt",
    "siberian",
    "chocolate",
    "egyptiankohl",
    "whixtensions",
    "skyblue",
    "missmuffett",
    "padparadscha",
    "butterscotch",
    "thicccbrowz",
    "hanauma",
    "cornflower",
    "camo",
    "sapphire",
    "scarlet",
    "mintmacaron",
    "salmon",
    "daemonhorns",
    "turtleback",
    "grimace",
    "frosting",
    "lilac",
    "razzledazzle",
    "belch",
    "apricot",
    "patrickstarfish",
    "alicorn",
    "topaz",
    "eclipse",
    "mittens",
    "hacker",
    "stunned",
    "hotcocoa",
    "wasntme",
    "caffeine",
    "birman",
    "cyan",
    "metime",
    "wolfgrey",
    "toyger",
    "tendertears",
    "manx",
    "samwise",
    "bananacream",
    "arcreactor",
    "lavender",
    "doridnudibranch",
    "simple",
    "vigilante",
    "moonrise",
    "peppermint",
    "purplehaze",
    "raisedbrow",
    "thunderstruck",
    "hintomint",
    "periwinkle",
    "spock",
    "garnet",
    "liger",
    "thundergrey",
    "crazy",
    "tigerpunk",
    "brownies",
    "baddate",
    "verdigris",
    "prairierose",
    "wuvme",
    "mainecoon",
    "jaguar",
    "cottoncandy",
    "beard",
    "confuzzled",
    "flapflap",
    "morningglory",
    "pouty",
    "peach",
    "trioculus",
    "nachocheez",
    "moue",
    "mintgreen",
    "atlantis",
    "summerbonnet",
    "bloodred",
    "candyshoppe",
    "robin"
  ],
  allColors: [
    {
      name: "olive",
      colorHex: "#729100",
      backgroundColorHex: "#ecf4e0",
      shadowColorHex: "#c8d6b4"
    },
    {
      name: "pinefresh",
      colorHex: "#177a25",
      backgroundColorHex: "#dbf0d0",
      shadowColorHex: "#adcf9b"
    },
    {
      name: "oasis",
      colorHex: "#ccffef",
      backgroundColorHex: "#e6faf3",
      shadowColorHex: "#bee1d4"
    },
    {
      name: "dioscuri",
      colorHex: "#0ba09c",
      backgroundColorHex: "#d1eeeb",
      shadowColorHex: "#a8d5d1"
    },
    {
      name: "isotope",
      colorHex: "#e4ff73",
      backgroundColorHex: "#effdca",
      shadowColorHex: "#cde793"
    },
    {
      name: "bridesmaid",
      colorHex: "#ffc2df",
      backgroundColorHex: "#ffd5e5",
      shadowColorHex: "#eba3bc"
    },
    {
      name: "downbythebay",
      colorHex: "#83b293",
      backgroundColorHex: "#cde5d1",
      shadowColorHex: "#97bc9c"
    },
    {
      name: "gemini",
      colorHex: "#ffd150",
      backgroundColorHex: "#faf4cf",
      shadowColorHex: "#e3daa1"
    },
    {
      name: "kaleidoscope",
      colorHex: "#bcba5e",
      backgroundColorHex: "#eff1e0",
      shadowColorHex: "#cfd4b0"
    },
    {
      name: "thundergrey",
      colorHex: "#828282",
      backgroundColorHex: "#eee9e8",
      shadowColorHex: "#dbccc7"
    },
    {
      name: "gold",
      colorHex: "#fcdf35",
      backgroundColorHex: "#faf4cf",
      shadowColorHex: "#e3daa1"
    },
    {
      name: "topaz",
      colorHex: "#0ba09c",
      backgroundColorHex: "#d1eeeb",
      shadowColorHex: "#a8d5d1"
    },
    {
      name: "mintgreen",
      colorHex: "#43edac",
      backgroundColorHex: "#cdf5d4",
      shadowColorHex: "#9ad7a5"
    },
    {
      name: "sizzurp",
      colorHex: "#7c40ff",
      backgroundColorHex: "#dfdffa",
      shadowColorHex: "#c1c1ea"
    },
    {
      name: "chestnut",
      colorHex: "#a56429",
      backgroundColorHex: "#efe1da",
      shadowColorHex: "#d4beb3"
    },
    {
      name: "strawberry",
      colorHex: "#ef4b62",
      backgroundColorHex: "#ffe0e5",
      shadowColorHex: "#efbaba"
    },
    {
      name: "sapphire",
      colorHex: "#4c7aef",
      backgroundColorHex: "#d3e8ff",
      shadowColorHex: "#a2c2eb"
    },
    {
      name: "forgetmenot",
      colorHex: "#4eb4f9",
      backgroundColorHex: "#dcebfc",
      shadowColorHex: "#a7caea"
    },
    {
      name: "dahlia",
      colorHex: "#b8bdff",
      backgroundColorHex: "#e6eafd",
      shadowColorHex: "#bec5e7"
    },
    {
      name: "coralsunrise",
      colorHex: "#Ff9088",
      backgroundColorHex: "#fde9e4",
      shadowColorHex: "#e7c3bb"
    },
    {
      name: "doridnudibranch",
      colorHex: "#Fa9fff",
      backgroundColorHex: "#faeefa",
      shadowColorHex: "#e1cce1"
    },
    {
      name: "parakeet",
      colorHex: "#49b749",
      backgroundColorHex: "#e5f3e2",
      shadowColorHex: "#bcd4b8"
    },
    {
      name: "cyan",
      colorHex: "#45f0f4",
      backgroundColorHex: "#c5eefa",
      shadowColorHex: "#83cbe0"
    },
    {
      name: "pumpkin",
      colorHex: "#ffa039",
      backgroundColorHex: "#fae1ca",
      shadowColorHex: "#efc8a4"
    },
    {
      name: "limegreen",
      colorHex: "#aef72f",
      backgroundColorHex: "#d9f5cb",
      shadowColorHex: "#b4d9a2"
    },
    {
      name: "bubblegum",
      colorHex: "#ef52d1",
      backgroundColorHex: "#fadff4",
      shadowColorHex: "#eebce3"
    },
    {
      name: "twilightsparkle",
      colorHex: "#Ba8aff",
      backgroundColorHex: "#ede2f5",
      shadowColorHex: "#dcc7ec"
    },
    {
      name: "palejade",
      colorHex: "#c3d8cf",
      backgroundColorHex: "#e7f1ed",
      shadowColorHex: "#c0d1ca"
    },
    {
      name: "eclipse",
      colorHex: "#484c5b",
      backgroundColorHex: "#e5e7ef",
      shadowColorHex: "#cdd1e0"
    },
    {
      name: "babypuke",
      colorHex: "#bcba5e",
      backgroundColorHex: "#eff1e0",
      shadowColorHex: "#cfd4b0"
    },
    {
      name: "autumnmoon",
      colorHex: "#ffe8bb",
      backgroundColorHex: "#fdf3e0",
      shadowColorHex: "#e7d4b4"
    }
  ]
});
export { UiStore };
