import firebase from "firebase/app";
import "firebase/firestore";
import { initFirestorter, Collection, Document } from "firestorter";
import config from "../firebase-config";

!firebase.apps.length ? firebase.initializeApp(config) : firebase.app();

initFirestorter({ firebase: firebase });
// let templateId;

const UiStore = new Document({ mode: "on" });
UiStore.hasMenu = false;
UiStore.allFancies = [
  { value: "Al", label: "Al" },
  { value: "Ande", label: "Ande" },
  { value: "Atlas", label: "Atlas" },
  { value: "Berry", label: "Berry" },
  { value: "Boot", label: "Boot" },
  { value: "Catamari", label: "Catamari" },
  { value: "Catbury", label: "Catbury" },
  { value: "Catyrax", label: "Catyrax" },
  { value: "ChatPlongeur", label: "ChatPlongeur" },
  { value: "Clover", label: "Clover" },
  { value: "Curdlin", label: "Curdlin" },
  { value: "DJMeowlody", label: "DJMeowlody" },
  { value: "DocPurr", label: "DocPurr" },
  { value: "Draco", label: "Draco" },
  { value: "DracoJunior", label: "DracoJunior" },
  { value: "Dracula", label: "Dracula" },
  { value: "Dreggo", label: "Dreggo" },
  { value: "DuCat", label: "DuCat" },
  { value: "Dukecat", label: "Dukecat" },
  { value: "Earnie", label: "Earnie" },
  { value: "Flutterbee", label: "Flutterbee" },
  { value: "Furbeard", label: "Furbeard" },
  { value: "Furrmingo", label: "Furrmingo" },
  { value: "GeneDough", label: "GeneDough" },
  { value: "Glasswalker", label: "Glasswalker" },
  { value: "Glitter", label: "Glitter" },
  { value: "Kitijira", label: "Kitijira" },
  { value: "KittyFormerlyKnownAsPrince", label: "KittyFormerlyKnownAsPrince" },
  { value: "KittyPride", label: "KittyPride" },
  { value: "Krakitten", label: "Krakitten" },
  { value: "Lulu", label: "Lulu" },
  { value: "Magmeow", label: "Magmeow" },
  { value: "Meowstro", label: "Meowstro" },
  { value: "MissPurrfect", label: "MissPurrfect" },
  { value: "MisterPurrfect", label: "MisterPurrfect" },
  { value: "Mistletoe", label: "Mistletoe" },
  { value: "Momo-chan", label: "Momo-chan" },
  { value: "Negato", label: "Negato" },
  { value: "Robin", label: "Robin" },
  { value: "Page", label: "Page" },
  { value: "Pawrula", label: "Pawrula" },
  { value: "Pawzilla", label: "Pawzilla" },
  { value: "PhuZiqaat", label: "PhuZiqaat" },
  { value: "Pickles", label: "Pickles" },
  { value: "Pizzazz", label: "Pizzazz" },
  { value: "PoisonOrchid", label: "PoisonOrchid" },
  { value: "Purrity", label: "Purrity" },
  { value: "Purrspero", label: "Purrspero" },
  { value: "PussForProgress", label: "PussForProgress" },
  { value: "Raspoutine", label: "Raspoutine" },
  { value: "SantaClaws", label: "SantaClaws" },
  { value: "SchrödingersCat", label: "SchrödingersCat" },
  { value: "SheilaPurren", label: "SheilaPurren" },
  { value: "ShipCat", label: "ShipCat" },
  { value: "Squib", label: "Squib" },
  { value: "Squiddlesworth", label: "Squiddlesworth" },
  { value: "Stitches", label: "Stitches" },
  { value: "Swish", label: "Swish" },
  { value: "Tabby", label: "Tabby" },
  { value: "TallyThePurrocious", label: "TallyThePurrocious" },
  { value: "Vernon", label: "Vernon" },
  { value: "Whisper", label: "Whisper" },
  { value: "YuriCatsuki", label: "YuriCatsuki" },
  { value: "咚咚锵", label: "DancingLion" },
  { value: "汪星爷", label: "Dogcat" },
  { value: "红包喵", label: "LuckyCat" }
];
UiStore.allAttributes = [
  "fangtastic",
  "pixiebob",
  "emeraldgreen",
  "tongue",
  "greymatter",
  "totesbasic",
  "palejade",
  "cyborg",
  "floorislava",
  "majestic",
  "buzzed",
  "manul",
  "dahlia",
  "norwegianforest",
  "sully",
  "rollercoaster",
  "harbourfog",
  "persian",
  "safetyvest",
  "seafoam",
  "inflatablepool",
  "prism",
  "wiley",
  "walrus",
  "sizzurp",
  "wyrm",
  "redvelvet",
  "hyacinth",
  "juju",
  "dali",
  "asif",
  "hotrod",
  "cashewmilk",
  "leopard",
  "limegreen",
  "unicorn",
  "lynx",
  "myparade",
  "buttercup",
  "icicle",
  "scorpius",
  "universe",
  "meowgarine",
  "wonky",
  "olive",
  "wowza",
  "swampgreen",
  "icy",
  "gyre",
  "kittencream",
  "otaku",
  "twilightsparkle",
  "bornwithit",
  "alien",
  "ruhroh",
  "mekong",
  "pumpkin",
  "ducky",
  "struck",
  "shadowgrey",
  "fox",
  "slyboots",
  "ganado",
  "drift",
  "strawberry",
  "splat",
  "swarley",
  "chronic",
  "featherbrain",
  "bridesmaid",
  "soserious",
  "calicool",
  "frozen",
  "shamrock",
  "downbythebay",
  "parakeet",
  "balinese",
  "cheeky",
  "royalpurple",
  "sphynx",
  "onyx",
  "kaleidoscope",
  "coffee",
  "foghornpawhorn",
  "littlefoot",
  "highlander",
  "orangesoda",
  "tinybox",
  "cymric",
  "daemonwings",
  "shale",
  "laperm",
  "pinefresh",
  "violet",
  "secretgarden",
  "azaleablush",
  "sandalwood",
  "finalfrontier",
  "happygokitty",
  "oasis",
  "fallspice",
  "babypuke",
  "junglebook",
  "rosequartz",
  "lykoi",
  "saycheese",
  "glacier",
  "pearl",
  "himalayan",
  "barkbrown",
  "dioscuri",
  "tiger",
  "dragonwings",
  "dreamboat",
  "martian",
  "allyouneed",
  "daffodil",
  "amur",
  "fabulous",
  "forgetmenot",
  "burmilla",
  "grim",
  "serpent",
  "sass",
  "belleblue",
  "firstblush",
  "topoftheworld",
  "satiated",
  "ooze",
  "chameleon",
  "henna",
  "koala",
  "chantilly",
  "impish",
  "oldlace",
  "bobtail",
  "salty",
  "firedup",
  "tundra",
  "coralsunrise",
  "cloudwhite",
  "dragontail",
  "lemonade",
  "avatar",
  "chartreux",
  "wingtips",
  "royalblue",
  "flamingo",
  "autumnmoon",
  "neckbeard",
  "rascal",
  "aflutter",
  "sweetmeloncakes",
  "dragonfruit",
  "oceanid",
  "rorschach",
  "dune",
  "gold",
  "cinderella",
  "spangled",
  "chestnut",
  "googly",
  "isotope",
  "mauveover",
  "starstruck",
  "granitegrey",
  "koladiviya",
  "mertail",
  "springcrocus",
  "luckystripe",
  "mallowflower",
  "ragdoll",
  "dippedcone",
  "bubblegum",
  "delite",
  "aquamarine",
  "munchkin",
  "gemini",
  "highsociety",
  "kurilian",
  "kalahari",
  "poisonberry",
  "elk",
  "gerbil",
  "roadtogold",
  "savannah",
  "selkirk",
  "jacked",
  "drama",
  "yokel",
  "ragamuffin",
  "cerulian",
  "cobalt",
  "siberian",
  "chocolate",
  "egyptiankohl",
  "whixtensions",
  "skyblue",
  "missmuffett",
  "padparadscha",
  "butterscotch",
  "thicccbrowz",
  "hanauma",
  "cornflower",
  "camo",
  "sapphire",
  "scarlet",
  "mintmacaron",
  "salmon",
  "daemonhorns",
  "turtleback",
  "grimace",
  "frosting",
  "lilac",
  "razzledazzle",
  "belch",
  "apricot",
  "patrickstarfish",
  "alicorn",
  "topaz",
  "eclipse",
  "mittens",
  "hacker",
  "stunned",
  "hotcocoa",
  "wasntme",
  "caffeine",
  "birman",
  "cyan",
  "metime",
  "wolfgrey",
  "toyger",
  "tendertears",
  "manx",
  "samwise",
  "bananacream",
  "arcreactor",
  "lavender",
  "doridnudibranch",
  "simple",
  "vigilante",
  "moonrise",
  "peppermint",
  "purplehaze",
  "raisedbrow",
  "thunderstruck",
  "hintomint",
  "periwinkle",
  "spock",
  "garnet",
  "liger",
  "thundergrey",
  "crazy",
  "tigerpunk",
  "brownies",
  "baddate",
  "verdigris",
  "prairierose",
  "wuvme",
  "mainecoon",
  "jaguar",
  "cottoncandy",
  "beard",
  "confuzzled",
  "flapflap",
  "morningglory",
  "pouty",
  "peach",
  "trioculus",
  "nachocheez",
  "moue",
  "mintgreen",
  "atlantis",
  "summerbonnet",
  "bloodred",
  "candyshoppe",
  "robin"
];

export { UiStore };
